'use client';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { X, Download, Copy, Upload, Save, RotateCcw, Trash2 } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
import { sendWorldCommand } from '@/lib/world/bridge';
import { DEFAULT_PRESENTATION, type WorldCommand, type WorldState } from '@/lib/world/commands';
import { DEFAULT_LIGHT, LIGHT_RANGES, SAVED_COMPOSITIONS, composition, parseComposition, validateComposition, type Composition, type LightNumber, type LightOptions } from '@/lib/terra/composition';
import styles from './composition-controls.module.css';
export type CompositionTab = 'light' | 'layers' | 'saved';
export function NumberSlider({name,label,value,onChange,note}: {name:LightNumber;label:string;value:number;onChange:(n:number)=>void;note?:string}) {
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState('');
 const percent=name==='warmth'||name==='colour';const unit=percent?100:1;const [lo,hi,increment] = LIGHT_RANGES[name];const min=lo*unit,max=hi*unit,step=increment*unit;
 return <div className={styles.sliderRow}><div className={styles.sliderHeading}><label htmlFor={`compose-${name}`}>{label}</label><label className={styles.number}><input aria-label={`${label} value`} type="number" min={min} max={max} step={step} value={editing?draft:Number((value*unit).toFixed(percent?0:2))} onFocus={()=>{setDraft(String(Number((value*unit).toFixed(percent?0:2))));setEditing(true);}} onBlur={()=>setEditing(false)} onChange={e=>{setDraft(e.target.value);if(e.target.value!==''&&e.target.validity.valid)onChange(+e.target.value/unit);}}/><span>{percent?'%':'×'}</span></label></div><input id={`compose-${name}`} style={{'--slider-fill':`${(value*unit-min)/(max-min)*100}%`} as CSSProperties} type="range" min={min} max={max} step={step} value={value*unit} aria-valuetext={percent?`${Math.round(value*100)} percent`:`${value.toFixed(2)} times`} onChange={e=>onChange(+e.target.value/unit)}/>{note&&<p className={styles.note}>{note}</p>}</div>;
}
const focusNames = {living:'Living Earth','night-lights':'Night lights',population:'Population',footprint:'Human footprint',connections:'Connections'} as const;
function readSaved() {
 try { const raw=JSON.parse(localStorage.getItem(SAVED_COMPOSITIONS)??'[]');return {items:Array.isArray(raw)?raw.slice(0,20).map(validateComposition).filter((v):v is Composition=>!!v):[],error:false}; }
 catch { return {items:[] as Composition[],error:true}; }
}
export function CompositionControls({tab,setTab,onClose,options,onChange,state,onApply,disabled}: {tab:CompositionTab;setTab:(v:CompositionTab)=>void;onClose:()=>void;options:LightOptions;onChange:(v:Partial<LightOptions>)=>void;state:WorldState|null;onApply:(v:Composition)=>Promise<void>;disabled:boolean}) {
 const [initialSaved]=useState(readSaved);
 const [message,setMessage]=useState(''),[name,setName]=useState('My Earth'),[saved,setSaved]=useState<Composition[]>(initialSaved.items),[transfer,setTransfer]=useState(''),[storageError,setStorageError]=useState(initialSaved.error),[undo,setUndo]=useState<Composition[]|null>(null);
 const closeRef=useRef<HTMLButtonElement>(null),upload=useRef<HTMLInputElement>(null),bodyRef=useRef<HTMLDivElement>(null);
 const p=state?.presentation??DEFAULT_PRESENTATION,local=state?.tier==='city'||state?.tier==='street';
 useEffect(()=>{closeRef.current?.focus();},[]);
 useEffect(()=>{if(bodyRef.current)bodyRef.current.scrollTop=0;},[tab]);
 useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[onClose]);
 const run=async(command:WorldCommand)=>{const r=await sendWorldCommand(command);setMessage(r.ok?'':r.reason??'That setting could not change. Try again.');};
 const snapshot=()=>composition(name,options,p,state?.layers);
 const persist=(next:Composition[])=>{try{localStorage.setItem(SAVED_COMPOSITIONS,JSON.stringify(next));setSaved(next);setStorageError(false);return true;}catch{setStorageError(true);setMessage('This browser cannot save settings. Export them to keep a copy.');return false;}};
 const slider=(key:LightNumber,label:string,note?:string)=><NumberSlider key={key} name={key} label={label} value={options[key]} onChange={v=>onChange({[key]:v})} note={note}/>;
 const toggle=(id:string,label:string,checked:boolean,change:(v:boolean)=>void)=><div className={styles.switchRow}><label htmlFor={id}>{label}</label><Switch id={id} checked={checked} onCheckedChange={change}/></div>;
 const apply=async(c:Composition)=>{try{await onApply(c);setName(c.name);setMessage(`Applied “${c.name}”.`);}catch(e){setMessage(e instanceof Error?e.message:'Settings could not be applied. Try again.');}};
 const exportSettings=()=>{const text=JSON.stringify(snapshot(),null,2);setTransfer(text);const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='terra-astra-composition.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Settings exported. Keep this file to restore or share your composition.');};
 return <aside id="composition-panel" className={styles.panel} aria-label="Compose your Earth">
  <header className={styles.heading}><h2>{tab==='light'?'Light, to your liking.':tab==='layers'?'Earth in layers.':'Your compositions.'}</h2><button ref={closeRef} onClick={onClose} aria-label="Close composition controls"><X size={19}/></button></header>
  <nav className={styles.tabs} aria-label="Composition controls">{(['light','layers','saved'] as const).map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>{setTab(t);setMessage('');}}>{t==='light'?'Light':t==='layers'?'Layers':'Saved'}</button>)}</nav>
  <div ref={bodyRef} className={styles.body}>
  {tab==='light'&&<><p className={styles.intro}>Keep Earth in view. Every change is live.</p>{slider('glow','Star glow')}{slider('shimmer','Star shimmer')}{slider('nightLights','Night-light intensity')}{slider('density','Land star density')}{slider('warmth','Land star warmth','A gentle shift between pearl and gold.')}{slider('threads','Constellation threads')}{slider('oceanLight','Ocean particles')}{toggle('compose-borders','Trace country boundaries',options.borders,borders=>onChange({borders}))}{toggle('compose-motion','Ambient motion',options.motion,motion=>onChange({motion}))}<button className={styles.textButton} onClick={()=>onChange({...DEFAULT_LIGHT,motion:options.motion})}><RotateCcw size={14}/> Restore the original light</button></>}
  {tab==='layers'&&<><label className={styles.selectLabel} htmlFor="composition-focus">Bring forward</label><select id="composition-focus" value={p.focus} disabled={disabled} onChange={e=>void run({type:'setPresentation',presentation:{focus:e.target.value as typeof p.focus}})}>{Object.entries(focusNames).map(([value,label])=><option key={value} value={value} disabled={local&&value!=='living'||(value==='population'||value==='footprint')&&state?.humanFields==='unavailable'}>{label}</option>)}</select>
  <p className={styles.note}>{p.focus==='night-lights'?'NASA, 2016. Light intensity is not population.':p.focus==='population'?'GPWv4, 2020 estimates. Artistically sampled population density.':p.focus==='footprint'?'Venter et al., 2009. A historical index of human pressure, sampled as light.':p.focus==='connections'?'Follow the illustrated air, sea and undersea pathways. No live tracking.':local?'Geographic lenses return at Planet or Region.':'White-gold stars remain the foundation. Add a little colour beneath them.'}</p>
  {p.focus!=='living'&&p.focus!=='connections'&&toggle('compose-keep','Keep transport visible',p.keepActivity,keepActivity=>void run({type:'setPresentation',presentation:{keepActivity}}))}
  <details className={styles.section} open><summary>Land &amp; colour</summary>{state?.humanFields==='unavailable'&&<p className={styles.status}>Geographic fields could not load. Reload to retry; the rest of Earth is available.</p>}{slider('population','Population light')}{slider('footprint','Human footprint light')}{slider('fieldDensity','Geographic particle density')}{slider('colour','Colour presence','Muted blue and violet, held beneath the warmer stars.')}</details>
  <details className={styles.section} open><summary>Paths &amp; travellers</summary>{p.focus!=='living'&&p.focus!=='connections'&&!p.keepActivity&&<p className={styles.status}>Transport is resting in this lens. Your choices are remembered.</p>}
   {toggle('compose-pathways','Pathways',p.pathways,pathways=>void run({type:'setPresentation',presentation:{pathways}}))}{slider('pathLight','Pathway intensity')}{slider('pathVolume','Pathway richness','Reveal more fine strands along the same illustrated corridors.')}
   {toggle('compose-travellers','Travellers & pulses',p.travellers,travellers=>void run({type:'setPresentation',presentation:{travellers}}))}{slider('travellerLight','Traveller intensity')}{slider('travellerVolume','Traveller density')}
  </details><details className={styles.section}><summary>Individual families</summary>{([['aircraft','Flights','airLight'],['ships','Ships','seaLight'],['cables','Undersea cables','cableLight'],['satellites','Satellites','orbitLight']] as const).map(([layer,label,key])=><div key={layer}>{toggle('compose-'+layer,label,state?.layers[layer]??true,enabled=>void run({type:'focusLayer',layer,enabled}))}{slider(key,`${label} intensity`)}</div>)}<p className={styles.note}>Satellites remain free of visible orbit lines.</p></details></>}
  {tab==='saved'&&<><p className={styles.intro}>Save this balance of light, layers and activity. Settings stay in this browser; export a copy to carry them elsewhere.</p><label className={styles.selectLabel} htmlFor="composition-name">Composition name</label><input id="composition-name" value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder="Evening over the Pacific"/><button className={styles.primary} disabled={disabled||!name.trim()} onClick={()=>{const c=snapshot(),same=saved.some(s=>s.name===c.name);if(!same&&saved.length>=20){setMessage('Twenty compositions are saved. Export or remove one before adding another.');return;}if(persist([...saved.filter(s=>s.name!==c.name),c]))setMessage(`Saved “${c.name}” in this browser.`);}}><Save size={15}/>{saved.some(s=>s.name===name.trim())?'Update saved composition':'Save composition'}</button>
  <div className={styles.savedList}>{saved.length===0?<p className={styles.note}>Your saved compositions will appear here.</p>:saved.map(c=><div key={c.name}><button disabled={disabled} onClick={()=>void apply(c)}><strong>{c.name}</strong><span>{focusNames[c.presentation.focus]} · glow {c.light.glow.toFixed(2)}×</span></button><button aria-label={`Remove ${c.name}`} onClick={()=>{setUndo(saved);if(persist(saved.filter(s=>s.name!==c.name)))setMessage(`Removed “${c.name}”.`);}}><Trash2 size={15}/></button></div>)}</div>{undo&&<button className={styles.textButton} onClick={()=>{if(persist(undo)){setUndo(null);setMessage('Composition restored.');}}}>Undo removal</button>}
  <div className={styles.transferActions}><button onClick={exportSettings}><Download size={15}/> Export</button><button onClick={()=>upload.current?.click()}><Upload size={15}/> Import</button><button onClick={async()=>{const text=JSON.stringify(snapshot(),null,2);setTransfer(text);try{await navigator.clipboard.writeText(text);setMessage('Exact settings copied. Paste them into our conversation.');}catch{setMessage('Copy is unavailable. Select the settings below to copy them.');}}}><Copy size={15}/> Copy</button></div>
  <input ref={upload} className={styles.fileInput} type="file" accept="application/json,.json" aria-label="Import composition file" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>32768){setMessage('That file is too large. Choose a Terra Astra settings export.');return;}try{const c=parseComposition(await file.text());if(!c){setMessage('Those settings are not a valid Terra Astra composition. Your view is unchanged.');return;}await apply(c);}catch{setMessage('The file could not be read. Try importing it again.');}}}/>
  <details className={styles.section}><summary>Paste or inspect exact settings</summary><textarea aria-label="Exact composition settings" value={transfer} onChange={e=>setTransfer(e.target.value)} maxLength={32768} spellCheck={false} rows={8}/><button disabled={disabled||!transfer} className={styles.textButton} onClick={()=>{const c=parseComposition(transfer);if(c)void apply(c);else setMessage('These settings are invalid or from an unsupported version. Your view is unchanged.');}}>Apply pasted settings</button></details>{storageError&&<p className={styles.note}>Browser storage is unavailable. Export settings before leaving.</p>}</>}
  {message&&<p className={styles.status} role="status">{message}</p>}
  </div><footer className={styles.footer}><span>{focusNames[p.focus]}</span><button onClick={()=>setTab(tab==='saved'?'light':'saved')}>{tab==='saved'?'Back to light':'Save this composition'}</button></footer>
 </aside>;
}
