/** User-facing release history. Keep historical entries tied to their saved milestones. */
export const currentVersion = '0.10.12';

export const releases = [
  {
    version: '0.10.12',
    date: '2026-09-16',
    dateLabel: '16 September 2026',
    title: 'Quiet pathways, passing light',
    milestone: 'Calm Earth · People’s Choice Lab',
    changes: [
      'Flights follow steady cruise corridors above the sculpted terrain. Their quiet pathways, brighter heads and short trails stay together through every turn.',
      'Shipping lanes curve through their ocean waypoints. Sea and cable branches gather smoothly at shared hubs, with restrained resting light and brighter passing travellers.',
      'Choose flights, ships, cables and satellites independently, or separate pathways from travellers. Activity returns in staggered groups over a few seconds; satellites retain no visible tracks.',
      'Night lights brings the sourced 2016 NASA pattern forward while transport gently recedes. Keep activity if desired, or return to Living Earth with previous choices intact.',
    ],
    review: 'Routes, cruise heights, waiting vessels and activity remain illustrative, not live tracking or navigation guidance. Two narrow straits and the surface canals remain schematic. Night-light brightness is not population. Population, road-density and human-footprint lenses await suitable sourced data. Earlier releases and canonical v0.10.8 are preserved.',
  },
  {
    version: '0.10.11',
    date: '2026-09-16',
    dateLabel: '16 September 2026',
    title: 'Subsea connections, drawn in light',
    milestone: 'Cable refinement · People’s Choice Lab',
    changes: [
      'Continuous fine lilac strokes reveal the existing undersea network, with soft edges and a restrained halo.',
      'Rounded, ocean-constrained bends replace angular waypoint joins. Coincident strands separate gently and gather at their existing offshore hubs.',
      'Quiet signal lights follow the same curves. Regional focus, sculpted depth, awakening and reduced motion retain the established behaviour.',
    ],
    review: 'The 116 routes and 50 offshore hub regions remain illustrative, not surveyed cable alignments or live network status. The Canvas fallback uses smooth point paths. Shipping-lane correction is a separate next pass; canonical remains at v0.10.8.',
  },
  {
    version: '0.10.10',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Open Earth — places beyond the five',
    milestone: 'Run G · People’s Choice Lab',
    changes: [
      'Find cities, islands, mountains and regions by name. Sourced place records guide the journey; ambiguous names offer a choice.',
      'Region opens into terrain, shores, nearby settlements and relevant connections, framed to the place’s geographic scale.',
      'Generic cities combine sourced local roads, simpler major corridors and interpretive metropolitan light. Local exploration moves through overlapping road neighborhoods as you travel.',
      'The five deeply authored destinations retain their special character. Sonic Earth, Genesis and the accepted planetary systems remain.',
    ],
    review: 'Road coverage depends on open data availability; missing detail returns to a broader view. Interpretive lights are not mapped streets, and activity is not live tracking. Phone viewport checks passed; physical-phone and authenticated Live listening remain owner QA. Canonical stays frozen at v0.10.8.',
  },
  {
    version: '0.10.9',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Ocean volume, flow and connected light',
    milestone: 'Run F · People’s Choice Lab',
    changes: [
      'Sparse suspended stars and eight interpretive current structures give the ocean a quiet water column above its sculpted floor.',
      '176 ships share 86 maritime structures, including regional branches, ocean bundles and schematic canal connections. 116 fine undersea paths gather around 50 offshore hub regions.',
      'Quiet signal journeys travel along the network. Regional focus brings nearby connections forward while distant paths recede; global layers fade before city and street exploration.',
      'Held WASD keys now move together with normalized diagonal speed. Releasing keys or leaving the canvas clears movement. The accepted Sonic Earth, 84 satellites, 200 aircraft and destination experiences remain.',
    ],
    review: 'Illustrative routes, hub regions and currents, not live tracking or actual cable alignments. Canonical remains frozen at v0.10.8. Physical mobile and authenticated Live listening remain owner QA; detailed evidence is in the Run F handoff.',
  },
  {
    version: '0.10.8',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Sonic Earth + Living Planet',
    milestone: 'Integrated Lab checkpoint',
    changes: [
      'The accepted Sonic Earth soundscape joins the accepted Living Planet: 84 satellites, 200 aircraft, 176 ships, 44 sea corridors and 56 undersea connections.',
      'Hear the living Earth follows the same Genesis, awakening, journeys and destinations. Sound remains optional, with the accepted volume and voice ducking.',
      'The richer planetary populations feed bounded, normalized sound activity. Their visual materials, depth, arrival readiness and history return are preserved.',
    ],
    review: 'Integration only. Both accepted source checkpoints and the v0.10.2 rollback remain preserved. Validation and listening limits are recorded in the integration handoff. People’s Choice Lab only.',
  },
  {
    version: '0.10.7',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Living Planet — the familiar orbital lights',
    milestone: 'Preserved Living Planet checkpoint',
    changes: [
      'Satellites return to the larger icy-cyan stars, brighter heads and trails, and original glimmer cadence of the accepted visual baseline.',
      'The orbital population stays at 84. Their smooth paths and 2.4-second trails retain the original feel, with the earlier approach fade restored.',
    ],
    review: 'Adjusted after owner review of the Lab. Air, maritime circulation, subsea connections and the arrival readiness repair remain intact. Earlier Living Planet checkpoints are preserved. Lab only.',
  },
  {
    version: '0.10.6',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Living Planet — ready at every scale',
    milestone: 'Preserved arrival checkpoint',
    changes: [
      'The Living Planet materials remain: 84 satellites, 200 aircraft, 176 vessels, 44 sea structures and 56 subsea paths.',
      'Direct entry into Singapore now releases the scale controls when detail finishes loading, including an instant arrival with reduced motion.',
    ],
    review: 'A served-site check exposed an inherited arrival notification race. The targeted regression reproduced it before the repair; native reduced-motion entry and scale navigation are rechecked. The visual Run D checkpoint remains preserved as v0.10.5. Lab only.',
  },
  {
    version: '0.10.5',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Living Planet — currents, journeys and connections',
    milestone: 'Preserved Living Planet checkpoint',
    changes: [
      '84 icy orbital lights, 200 atmospheric journeys and 176 slower maritime lights keep their own heights, trails and glimmer rhythms.',
      '44 soft sea corridors carry the ships through ocean basins and coastal approaches. The circulation follows the bundled ocean geography.',
      '56 lilac undersea connections gather into trunks and branches, visible from orbit and seated above the sampled seafloor in depth views.',
      'Global layers gain presence at regional scale and recede before city and street detail. Genesis, awakening and the five destinations remain connected.',
    ],
    review: 'Visual Run D starts from the preserved v0.10.2 baseline. Routes and activity are authored illustrations, never live tracking, actual cable alignments or navigation guidance. Radii, light and time are exaggerated for perception. Verification receipts accompany this release; physical-phone testing remains separate. People’s Choice Lab only.',
  },
  {
    version: '0.10.4',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Return to the living Earth',
    milestone: 'People’s Choice Lab · Navigation repair',
    changes: [
      'Repairs the return links on Build history so they open Earth reliably.',
      'Preserves the provisionally accepted Sonic Earth soundscape, its optional activation and all world behavior.',
    ],
    review: 'The v0.10.3 publication check exposed a framework navigation failure on the history page. Its return links now use normal document navigation, matching the entry into history and ensuring a fresh, silent Earth. Audio and listening limitations remain those recorded for v0.10.3.',
  },
  {
    version: '0.10.3',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Hear the living Earth — Sonic Earth',
    milestone: 'People’s Choice Lab · Accepted for now',
    changes: [
      'A small sound control invites you to hear Earth after it settles. Every fresh visit starts silently; sound remains optional throughout the journey.',
      'An original evolving harmonic field brings warmth to Earth. Sustained opening tones leave after awakening; later phrases change note order, spacing, voicing and register, with pauses between them. Approaching activity reveals extra detail.',
      'New York, Singapore and Palm follow their road and coastal activity. Makkah uses only its interpretive circular movement; Challenger Deep becomes quieter and darker with descent.',
      'Astra’s actual voice output lowers the world gently. Mute, hidden tabs, replay and interrupted sessions release or suspend the sound cleanly.',
    ],
    review: 'Accepted provisionally by the owner after iterative listening: workable for now, with further sound design needed. The owner requested an original cinematic harmonic layer after the texture-led candidates, then less drone and more variation. No recordings or borrowed score are used. Makkah retains only its existing movement interpretation at local scale. A separate QA browser was found capable of overlapping playback and was silenced; earlier listening may have been affected. Physical-device audio and authenticated GPT-Live-1 intelligibility are not certified by the engineering checks. The v0.10.2 tag and Lab saved version 4 remain the rollback. Canonical and the immutable v0.9 archive are untouched.',
  },
  {
    version: '0.10.2',
    date: '2026-09-14',
    dateLabel: '14 September 2026',
    title: 'Earth has form — Terrain, ocean and planetary depth',
    milestone: 'Preserved terrain checkpoint',
    changes: [
      'Mountains rise more clearly at low angles. Quiet lowlands, pale ridges and warm settlements retain the celestial Earth.',
      'A faint ocean surface awakens after ships and hidden connections. Shelves and seafloor sit beneath it; the existing ocean samples carry both layers.',
      'Horizon reveals surface form, Cutaway exposes the interior, and Surface reference holds the camera while the relief flattens. Challenger Deep’s light now descends to sampled bathymetry.',
      'Aircraft clear the sculpted land. Ships, cables, destinations, Genesis and the awakening order retain their existing roles.',
    ],
    review: 'Compared with preserved v0.10.1 in native Mac WebGL at desktop, 390×844 and 375×667. Globe, depth views, five destinations, supported scales, replay, early Astra input and graphics recovery were exercised. Relief remains artistically exaggerated; ocean flow and interior light are interpretive. Physical-phone and authenticated voice testing remain separate. People’s Choice Lab only.',
  },
  {
    version: '0.10.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Earth takes a breath — Post-Genesis awakening',
    milestone: 'Preserved awakening checkpoint',
    changes: [
      'Earth settles into a quiet 2.5-second breath. Orbit, aircraft, ships and hidden sea connections then awaken progressively, reaching the full living world within 18 seconds.',
      'The same lights and routes appear in a repeatable order, with tails growing behind their own objects. The idle Earth turns gently faster.',
      'Ask Astra stays available immediately; its first suggested journey arrives with the beginning of orbital life. Choosing a destination moves straight away.',
      'Replay clears the living shells and repeats the breath. Reduced motion reaches a full still Earth immediately, with no extended wait or animated trails.',
    ],
    review: 'Compared visually with Run A in native Mac WebGL at desktop and phone widths. The five destinations, supported scale transitions, early input, replay and reduced motion were exercised alongside renderer lifecycle tests. Physical-phone and microphone/audio verification remain separate. Published only to the People’s Choice Lab; canonical v0.9 and its archive remain preserved.',
  },
  {
    version: '0.10.0',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Follow a light — People’s Choice Run A',
    milestone: 'Preserved Run A',
    changes: [
      'A quiet invitation arrives after Earth settles. Try New York in one tap, or open Ask Astra for Makkah, Palm Jumeirah and Challenger Deep. Exploration works without sign-in; voice has a clear sign-in path.',
      'Five editorial destination choices reveal why each place is worth exploring. Phone controls give the headline and Earth their own space.',
      'Mapped city cores blend into selected peripheral structure and a sparse wider constellation. New York and Singapore share the same bounded continuation system with Palm and Makkah.',
      'Palm retains its warm designed geometry; Makkah’s soft collective flow gains continuous spacing and a varied cadence around the mapped Kaaba anchor.',
    ],
    review: 'Run A is published only to the People’s Choice Lab. Canonical v0.9 and its immutable archive remain separate. Surrounding city structure and activity are interpretive, never surveyed street extensions or live tracking. Desktop and narrow browser verification is recorded in the Run A handoff; physical-phone testing remains unverified.',
  },
  {
    version: '0.9',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Ready for the journey',
    milestone: 'Preserved v0.9 control',
    changes: [
      'Stopping Live releases the microphone immediately while the session finishes closing. A disconnected session can restart from Talk.',
      'Singapore and New York surroundings receive a small luminance adjustment to soften the change from their detailed cores.',
      'The same Genesis, five destinations, living shells and WorldCommand interface remain in place.',
    ],
    review: 'GPT-Live-1 voice requires ChatGPT sign-in and microphone permission. The public v0.8 session successfully transcribed a spoken Palm Jumeirah request, moved the world and closed. This patch adds immediate microphone release and retains final session usage handling. Activity remains illustrative; physical-phone testing remains unverified.',
  },
  {
    version: '0.8',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Different places, different motion',
    milestone: 'Previous release',
    changes: [
      'Palm Jumeirah adds its mapped trunk, fronds and crescent, surrounding Dubai coast, and warm activity along curated local roads.',
      'Makkah adds Masjid al-Haram context and a source-derived Kaaba anchor. Soft collective movement circulates counter-clockwise, with a persistent interpretive-flow disclosure.',
      'Both destinations use the existing world-command interface, renderer and fast scale navigation. Genesis, Singapore, New York and Challenger Deep remain connected.',
      'YC’s Live voice transport and typed navigation share the existing five-target WorldCommand path. A short acknowledgement precedes movement, with context after arrival.',
    ],
    review: 'These destinations use bounded OpenStreetMap snapshots. Activity is procedural and illustrative, never live tracking, crowd counts or route guidance. Makkah is an abstract celestial study, not a photorealistic or architectural survey. Physical-phone performance remains unverified. Live audio and general answers require server configuration and ChatGPT sign-in; a successful microphone conversation has not yet been verified on this publication. Typed catalogue navigation works without those services. The v0.7.1 source and saved publication remain available as the fallback.',
  },
  {
    version: '0.7.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'Stay with the place you chose',
    milestone: 'Previous release',
    changes: [
      'The primary journey button follows the selected destination: regional New York returns to New York city detail, and Challenger Deep returns to the planet.',
      'These actions use the existing world-command path and fast scale transitions. Singapore remains the opening destination.',
    ],
    review: 'Native Mac review confirms New York regional re-entry stays in New York (1.21 seconds), and Challenger Deep returns to planet (1.19 seconds) with Singapore available again. The v0.7 rendering, geography and keyboard controls are unchanged. YC Live conversation remains a separate integration.',
  },
  {
    version: '0.7',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A wider, more responsive world',
    milestone: 'Previous release',
    changes: [
      'Repeated scale changes now travel in 1.1 seconds. Singapore and New York detail prepares after Genesis, and cold journeys begin moving before detail arrives.',
      '72 orbital lights, 120 aircraft and 24 ships occupy distinct heights and routes. Faint violet undersea connections and two distant star shells extend the world around Earth.',
      'Dim, impressionistic city fields continue beyond the mapped Singapore and lower-Manhattan cores. Road traffic follows route length and connectivity; softer activity gathers around junctions.',
      'Focused-canvas navigation adds WASD, Q/E, R/F, T/G, scales 1–4 and reset 0. Text-entry and browser shortcuts remain separate.',
    ],
    review: 'Native Mac WebGL measured warm City to Street and Street to Region at about 1.2 seconds, compared with 6.9 seconds in v0.6.1. Rolling rendering remained near 120 fps in these samples. Source checks cover Genesis endpoints, loading and command settlement, geographic routes, cached continuation and keyboard guards. Movement and surrounding city fields are illustrative, not live tracking or surveyed extensions. Physical-phone performance and the separate YC Live conversation integration remain unverified.',
  },
  {
    version: '0.6.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A clearer view into the deep',
    milestone: 'Previous release',
    changes: [
      'Challenger Deep arrives in the existing angled Horizon view, with clearer seafloor particles at regional scale.',
      'The terrain selector names the active destination. Regional approaches use matching journey language.',
    ],
    review: 'Native WebGL review confirms the angled Mariana view, geographic focus and matching controls. Regional zoom, resizing, perspective switching and the Surface reference pass regression checks. Genesis, planetary exposure and city rendering are unchanged. The v0.6 video remains the recorded living-Earth milestone; YC Live integration is still pending.',
  },
  {
    version: '0.6',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A world born from stars',
    milestone: 'Previous release',
    changes: [
      'A dense nucleus compresses, ignites and ejects its particles into space. The same particles curve home to form geographic Earth.',
      'Sparse icy orbital lights and fast aqua atmospheric trails move above the planet. Subtle surface motion and relief preserve its celestial depth.',
      'Travel through planet, region, city and street scales. Singapore retains its detailed journey; curated lower Manhattan adds a second city in motion.',
      'Warm road traffic follows bundled street geometry, with softer activity around the city. These are deterministic visualisations, not live tracking.',
      'Singapore, New York and Challenger Deep share a small world-command interface prepared for Astra navigation. The manual controls use that same interface.',
    ],
    review: 'Native WebGL reviewed at desktop and phone widths, including the full genesis, paused Earth, destination controls, New York streets and Singapore descent. Automated checks cover immutable geographic endpoints, replay, reduced motion, movement shells, scale changes, geographic highlights, zoom, resizing and graphics interruption. Physical-phone performance remains unverified. Astra coordinated separate renderer, signal and urban engineering tracks; YC owns Live conversation integration, which is not included in this milestone.',
  },
  {
    version: '0.5',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A universe within',
    milestone: 'Previous release',
    changes: [
      'Open the geographic Earth into a layered stellar spiral, then reform the same particles into their original Earth.',
      'Choose three meaningful places from a sourced 48-place catalogue. Their geographic distances shape a constellation of your own.',
      'Return to Earth with your three warm stars and their connections still present: The constellation was us all along.',
      'Personal constellations survive the Singapore journey. Draft reset, change places, clear and full restart have separate meanings.',
      'Both WebGL and the reduced-detail Canvas renderer share the reversible transformation.',
    ],
    review: 'Native WebGL reviewed at desktop and phone widths: opening, three-place entry, warm constellation, closing return, draft reset and a Singapore round trip. Source checks cover immutable home positions, dateline and antipodal cases, repeated reversal and reduced motion. Physical-phone performance remains unverified. Astra coordinated isolated engineering tracks in Codex; no runtime inference is required. The v0.4 prototype and prepared geography predate the hackathon.',
  },
  {
    version: '0.4.1',
    date: '2026-09-13',
    dateLabel: '13 September 2026',
    title: 'A journey you can return to',
    milestone: 'Previous release',
    changes: [
      'Restart journey returns to the opening Earth with fresh camera, light and story settings.',
      'The home globe fits the desktop composition and adjusts when the window changes size.',
      'Switching between lives preserves the space above the story panel on narrow screens.',
      'A graphics interruption now offers a clear restart instead of dismissing a frozen view.',
    ],
    review: 'Reviewed in native WebGL on a Mac browser, including paused depth views, Singapore, all three lives at phone width, and remembered return. Geography, camera, lifecycle and build checks pass. Phone-width browser review is not physical-phone testing. This sprint continues the pre-existing v0.4 prototype; runtime Astra inference is not part of this release.',
  },
  {
    version: '0.4',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A world with depth',
    milestone: 'Previous release',
    changes: [
      'Real land elevation and ocean-floor relief shape the stars, with exaggerated height to reveal mountains, shelves and trenches.',
      'Layers of stellar matter, soft light and quiet cavities give the world an interior.',
      'Globe, Horizon and Cutaway offer three perspectives on the same Earth. Explore Indonesia and the Java Trench, or the Andes and Pacific.',
      'The Surface reference holds the camera still while you compare the added depth. Pausing motion also holds the shimmer.',
      'The Singapore journey and remembered-life return remain connected to this fuller Earth. Earlier releases are preserved.',
    ],
    review: 'Actual relief data and engine checks pass, including comparison, close zoom and all three lives. Paused desktop and phone-width views were reviewed using the Canvas fallback. Native WebGL appearance and physical-phone performance remain to be reviewed. Interior material is imagined.',
  },
  {
    version: '0.3',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A light you remember',
    milestone: 'Previous release',
    changes: [
      'Independent star rhythms, sharper occasional glints and a fuller glow make the Earth shimmer.',
      'A new Star shimmer control adjusts the effect. Pausing motion keeps the light still.',
      'The last life you visit stays with you after closing its story, gathering into a warm light on the way back to Earth.',
      'The globe settles before the closing words appear. A journey without a visited life has its own neutral return.',
      'Portrait returns allow more room for the remembered light; city point density responds to screen size.',
    ],
    review: 'Source, engine-lifecycle and projected-camera checks cover all three lives, fresh journeys and reduced motion. This release still needs an on-device visual review; earlier fallback screenshots describe v0.2.',
  },
  {
    version: '0.2.1',
    date: '2026-09-12',
    dateLabel: '12 September 2026',
    title: 'A history to build on',
    milestone: 'Saved milestone',
    changes: [
      'A visible version number opens this build history.',
      'Each milestone records its changes and review notes.',
      'The original globe and the v0.2 refinement are preserved as separate snapshots.',
    ],
    review: 'Uses the v0.2 star field. Full WebGL appearance and physical phone performance still need a device review.',
  },
  {
    version: '0.2',
    date: '2026-09-09',
    dateLabel: '9 September 2026',
    title: 'Continuity, light and the human reveal',
    milestone: 'Saved milestone',
    changes: [
      'The camera pulls away from Singapore before turning back toward the globe.',
      'Street detail appears gradually, with quieter light and softer coverage edges.',
      'Choosing a life dims the city, reveals its places and traces their connections.',
      'Stories begin with one sentence and expand on request. Phone framing keeps their places above the panel.',
    ],
    review: 'Camera regression checks and desktop / phone-width fallback checks passed. Saved separately before being included in v0.2.1.',
  },
  {
    version: '0.1',
    date: '2026-09-09',
    dateLabel: '9 September 2026',
    title: 'Earth, constellated',
    milestone: 'Original release',
    changes: [
      'A rotating Earth made from geographic star samples and historical city lights.',
      'A guided descent into central Singapore and three imagined human constellations.',
      'Controls for glow, density, connecting threads and ambient motion.',
    ],
    review: 'Owner screenshots and a recording informed the next pass: city brightness, transition continuity and the human reveal needed work.',
  },
] as const;
